/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mtzijin_androidtcpdumpsdk_TcpDumpInterface */

#ifndef _Included_com_mtzijin_androidtcpdumpsdk_TcpDumpInterface
#define _Included_com_mtzijin_androidtcpdumpsdk_TcpDumpInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mtzijin_androidtcpdumpsdk_TcpDumpInterface
 * Method:    cinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mtzijin_androidtcpdumpsdk_TcpDumpInterface_cinit
  (JNIEnv *, jobject);

/*
 * Class:     com_mtzijin_androidtcpdumpsdk_TcpDumpInterface
 * Method:    cstart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mtzijin_androidtcpdumpsdk_TcpDumpInterface_cstart
  (JNIEnv *, jobject);

/*
 * Class:     com_mtzijin_androidtcpdumpsdk_TcpDumpInterface
 * Method:    cfinal
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mtzijin_androidtcpdumpsdk_TcpDumpInterface_cfinal
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
